image: python:3.10-slim  # Specify the Docker image with Python

# Define stages
stages:
  - test
  - build
  - deploy

# Run the test suite before building or deploying a release.
test:
  stage: test
  script:
    - python -m pip install --upgrade pip
    - python -m pip install -e ".[dev]"
    - python -m pytest

# Job to build the package
build_package:
  stage: build
  image: python:3.10
  before_script:
    - python -m pip install --upgrade pip build
  script:
    - python -m build
  only:
    - tags
  artifacts:
    paths:
      - dist/

# Job to deploy to PyPI
deploy_pypi:
  stage: deploy
  image: python:3.10-slim
  variables:
    TWINE_USERNAME: __token__
    TWINE_PASSWORD: $PYPI_PASSWORD_IVORY

  script:
    - pip install twine
    - twine upload  dist/*
  only:
    - tags
  dependencies:
    - build_package
