[pytest]
addopts = --capture=sys
filterwarnings =
    ignore::madsci.common.warnings.MadsciLocalOnlyWarning
    ignore::UserWarning
    ignore:The wait_for_logs function with:DeprecationWarning:testcontainers
    ignore:The @wait_container_is_ready decorator is deprecated:DeprecationWarning:testcontainers
    ignore:ExperimentApplication is deprecated:DeprecationWarning
    ignore:NodeDefinition is deprecated:madsci.common.deprecation.MadsciDeprecationWarning
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
