/* Guia do painel (aba "Guia"): os textos de cada aba, figura, controle e conceito.
   app.js chama window.AUGO_GUIDE(A, h) e desenha a aba; os números vêm dos dados (A), então o texto acompanha as
   análises. FIG tem uma entrada por gráfico ou tabela do site, pela id do elemento; o teste
   test_guia_cobre_todas_as_figuras confere que nenhum ficou de fora. */
window.AUGO_GUIDE = function (A, h) {
  "use strict";
  const { nf, ni, esc, pf } = h;
  const v = (fn, d = "—") => { try { const x = fn(); return x == null || (typeof x === "number" && !isFinite(x)) ? d : x; } catch (e) { return d; } };
  const k = A.overview.kpis, L = A.literature, O = A.optics, D = A.designer, B = A.benchmark, I = A.interpret;
  const V = A.variability, C = A.causal, X = A.xrd, U = A.aunc, P = A.predictor;
  const E = (key) => C.effects.find((e) => e.key === key) || {};
  const ag = B.datasets.AgNP || {}, agS = v(() => ag.survival.vs_random["GP-EI"], {});
  const nTabs = 12;

  /* ------------------------------------------------------------------------------------------------ abas */
  const TABS = {
    visao: {
      purpose: "A página de entrada. Resume, em números, o que os dados experimentais já dizem sobre o problema do projeto: produzir nanopartículas de ouro (AuNP) do tamanho e da cor certos mesmo quando a matéria-prima (o óxido de grafeno, GO) muda de lote para lote.",
      data: `Todas as bases usadas no site: ${ni(k.literature_records)} sínteses de ouro relatadas em ${ni(k.literature_dois)} artigos, ${ni(k.agnp_measurements)} medidas de uma campanha de laboratório autônomo, quatro outras campanhas publicadas, ${ni(k.aunc_entries)} nanoaglomerados fluorescentes, quadros de difração de raios X e as constantes ópticas medidas do ouro.`,
      controls: [["Botões da abertura", "\"Testar o AuNP Designer\", \"Ver os achados\" e \"Mie e perda J\" levam direto à parte correspondente."],
        ["Faixa de cores do ouro", "Passe o mouse sobre a faixa: aparece o diâmetro e a cor que uma dispersão de partículas desse tamanho tem de verdade."],
        ["Cartões de achados", "Cada cartão é um resultado; clicar abre a aba com a análise completa."],
        ["Mapa das 18 seções", "Cada seção da proposta FAPESP aparece com o estado dela; clicar leva à aba onde ela está."]],
      take: "Se você só tiver um minuto, leia os oito cartões de achados e a tabela \"Os resultados conferem com a literatura?\": eles dizem o que foi medido e se bate com o que a ciência já sabia.",
    },
    literatura: {
      purpose: "Mostra o que já foi publicado sobre síntese de nanopartículas de ouro: quais reagentes as pessoas usam, que tamanhos e formas obtêm e como isso mudou com o tempo. É a \"memória coletiva\" da área, o ponto de partida antes de ir ao laboratório.",
      data: `${ni(L.n)} sínteses de três bases públicas (Cruse et al. 2022: ${ni(v(() => L.n_by_source["Cruse et al. 2022"]))}; NSP 2026: ${ni(v(() => L.n_by_source["NSP 2026"]))}; AuNCs 2025: ${ni(v(() => L.n_by_source["AuNCs 2025"]))}), extraídas automaticamente do texto dos artigos (mineração de texto) e com os nomes dos reagentes padronizados pelo dicionário PubChem. ${ni(L.n_go)} registros de ${ni(L.n_go_doi)} artigos mencionam óxido de grafeno.`,
      controls: [["Base", "Escolhe uma das três bases ou todas."],
        ["Redutor", "O reagente que transforma o sal de ouro (Au³⁺) em ouro metálico (Au⁰). Citrato é suave (partículas de 10–20 nm), NaBH₄ é forte (partículas de 1–8 nm)."],
        ["Ligante", "A molécula que cobre a superfície e impede que as partículas grudem (CTAB, PVP, tióis…)."],
        ["Morfologia", "Forma relatada: esfera, bastão, aglomerado, estrela, cubo…"],
        ["Rota", "Direta (tudo num passo) ou mediada por sementes (primeiro partículas pequenas, depois crescimento)."],
        ["Só GO", "Mostra apenas os registros que mencionam óxido de grafeno, o material do projeto."],
        ["Limpar filtros", "Volta para todas as sínteses."]],
      take: "A mesma receita aparece com tamanhos muito diferentes em artigos diferentes. Essa dispersão é a variabilidade entre fontes que o projeto quer controlar.",
    },
    optica: {
      purpose: "Liga o tamanho da partícula à cor e ao espectro de absorção (o que se mede no espectrofotômetro UV-Vis) usando a teoria de Mie, a física exata da luz espalhada por uma esfera. Também calcula a perda J, o número que o projeto usa para dizer quão perto o espectro está do alvo.",
      data: `Constantes ópticas medidas do ouro (Johnson & Christy 1972) e ${ni(O.lit_spheres.n)} pares tamanho–pico de esferas relatados na literatura, usados para validar a física.`,
      controls: [["Diâmetro médio", "Tamanho médio das partículas, de 2 a 150 nm."],
        ["Dispersão σ", "Quão diferentes as partículas são entre si (desvio relativo). 8 % é uma amostra muito uniforme; 30 % é bem heterogênea."],
        ["Normalização", "\"pelo máximo\" compara só a forma do espectro (como a perda J); \"por volume de Au\" compara quanto cada tamanho absorve com a mesma quantidade de ouro."],
        ["Exemplos", "Botões com receitas típicas (alvo do projeto, Turkevich, partículas grandes…)."],
        ["Concentração (A₀)", "Muda só a intensidade da cor da cubeta, como diluir ou concentrar a amostra."],
        ["Pico medido / a priori", "Controles da inversão bayesiana: escolha o pico de absorção que você mediu e veja que tamanhos são compatíveis."]],
      take: `A física funciona: sem nenhum ajuste, Mie erra o pico relatado por ${nf(k.mie_median_abs_residual, 1)} nm em mediana. Mas abaixo de ~25 nm o pico quase não muda com o tamanho, então o UV-Vis sozinho não basta para medir o tamanho do alvo (20 nm).`,
    },
    designer: {
      purpose: "Demonstra o AuNP Designer, o \"cérebro\" do projeto, numa campanha real de laboratório: um modelo estatístico (processo gaussiano, GP) aprende como as condições de síntese afetam o resultado e sugere o próximo experimento.",
      data: `Mekki-Berrada et al. (2021): ${ni(D.n_measurements)} medidas de nanopartículas de prata produzidas em microfluídica, em ${ni(D.n_conditions)} condições diferentes (cinco vazões de reagentes). O resultado medido é uma perda espectral contra um espectro-alvo, o mesmo papel da perda J no projeto.`,
      controls: [["Cinco controles deslizantes", "As cinco vazões (AgNO₃, PVA, citrato, sementes e vazão total). O GP recalcula na hora a perda prevista e a incerteza."],
        ["Eixos da superfície", "Quais duas variáveis aparecem na superfície 3D; as outras três ficam nos valores dos controles."],
        ["Superfície", "\"perda prevista\" (o que o modelo espera), \"incerteza\" (quanto ele não sabe) ou \"EI\" (o quanto vale a pena testar ali)."],
        ["Voltar à melhor medida", "Leva os controles à melhor condição medida na campanha."],
        ["Carregar (tabela de sugestões)", "Leva uma das condições sugeridas aos controles."]],
      take: `O GP explica ${nf(100 * k.designer_cv_r2, 0)} % da variação das medidas em validação cruzada e as suas faixas de incerteza estão bem calibradas.`,
    },
    preditor: {
      purpose: "Uma calculadora para antes da bancada: você monta uma receita e o site diz que tamanho de partícula a literatura relata para ela, com uma faixa honesta de incerteza, a chance de acertar o seu alvo, a cor esperada e as receitas publicadas mais parecidas.",
      data: `${ni(P.n)} sínteses de ${ni(P.n_articles)} artigos (as três bases da aba Literatura com tamanho entre 1 e 300 nm), ${ni(P.recipes.length)} receitas distintas.`,
      controls: [["Receitas prontas", "Preenchem o formulário com protocolos clássicos (Turkevich, Brust, sementes + CTAB…)."],
        ["Redutores e ligantes", "Clique para incluir ou tirar cada reagente; o número pequeno é quantas sínteses da base usam aquele reagente."],
        ["Rota", "Direta ou mediada por sementes."],
        ["Forma relatada", "Esfera, bastão, aglomerado ou outra forma."],
        ["Temperatura / não informada", "Temperatura da síntese; marque \"não informada\" se não souber."],
        ["Ano do relato", "Corrige a época (a forma de medir e relatar mudou ao longo dos anos)."],
        ["Base de referência / menciona GO", "De qual base o relato viria e se a síntese envolve óxido de grafeno."],
        ["Alvo", "O tamanho que você quer obter; usado na probabilidade de acerto, no \"o que mudar\" e no design inverso."]],
      take: `Os intervalos são honestos (o de 90 % contém o tamanho de ${nf(100 * P.bands["90"].coverage_articles, 0)} % dos artigos que o modelo nunca viu), mas são largos: só com a receita escrita no artigo o tamanho fica indeterminado num fator de ~${nf(P.bands["90"].median_fold_width, 0)}.`,
    },
    aprendizado: {
      purpose: "Responde: deixar um algoritmo escolher o próximo experimento economiza trabalho de verdade? Reexecuta cinco campanhas experimentais publicadas com diferentes estratégias de escolha e conta quantos experimentos cada uma precisa para achar uma das melhores condições.",
      data: `${B.seeds} repetições de cada estratégia em cada uma de ${Object.keys(B.datasets).length} campanhas reais (AgNP; e quatro de Liang et al. 2021: filmes P3HT/CNT, perovskitas, estruturas impressas \"crossed barrel\" e manufatura aditiva AutoAM). Cada vez que uma estratégia escolhe uma condição, ela recebe a medida real dessa condição.`,
      controls: [["Campanha", "Qual das cinco campanhas mostrar."],
        ["Comparar com o aleatório", "Qual estratégia (GP-EI, GP-UCB, RF-EI) colocar lado a lado com o sorteio."]],
      take: `No AgNP, o GP-EI chega ao top 5 % com ${nf(-agS.rmst_diff, 1)} experimentos a menos que o sorteio, em média. O ganho aparece nos espaços de busca grandes e some nos pequenos (~100 condições).`,
    },
    interpretabilidade: {
      purpose: "Abre a \"caixa-preta\" dos modelos: mostra quais variáveis mais pesam no resultado, em que direção e quais agem em conjunto.",
      data: "Três modelos: o GP da campanha AgNP (aba Designer), um modelo do deslocamento de Stokes dos nanoaglomerados fluorescentes e o modelo de tamanho da literatura (aba Preditor).",
      controls: [["Modelo", "Qual dos três modelos explicar."], ["Variável da dependência", "Qual variável aparece no gráfico de dependência."]],
      take: "AgNO₃ e sementes são as vazões que mais movem o resultado na campanha AgNP; um quarto da variação vem de combinações de vazões, não de cada uma sozinha.",
    },
    variabilidade: {
      purpose: "Mede a premissa central do projeto: a mesma receita não dá o mesmo produto. Separa o ruído de repetir a mesma síntese (réplicas) da variação entre laboratórios e artigos.",
      data: `${ni(V.agnp.n_measurements)} réplicas da campanha AgNP, ${ni(V.turkevich.n_papers)} artigos que usam a mesma rota clássica (Turkevich) e ${ni(v(() => V.aunc_generalization.n_papers))} artigos de nanoaglomerados.`,
      controls: [],
      take: `A mesma rota de Turkevich dá de ${nf(V.turkevich.q10_q90[0], 0)} a ${nf(V.turkevich.q10_q90[1], 0)} nm (80 % dos artigos), mediana ${nf(V.turkevich.median, 1)} nm, exatamente o valor clássico de Frens (1973).`,
    },
    causal: {
      purpose: "Vai além de \"A aparece junto com B\": estima quanto um reagente CAUSA de mudança no tamanho ou na forma, corrigindo os fatores que confundem a comparação, e confere cada resultado com o que a química prevê.",
      data: `Sínteses das bases Cruse 2022 e NSP 2026 (a base de nanoaglomerados fica de fora porque foi selecionada pelo produto) e, para os efeitos intervencionais, a campanha AgNP.`,
      controls: [["Diagnóstico do efeito", "Escolhe qual dos quatro efeitos detalhar nos gráficos de estimadores, balanço e sobreposição."]],
      take: `Os quatro efeitos estimados têm a direção que a literatura prevê (NaBH₄ deixa as partículas ×${nf(E("redutor").estimate, 2)} do tamanho com citrato) e se repetem em duas bases independentes.`,
    },
    caracterizacao: {
      purpose: "Mostra dados brutos de instrumentos: a difração de raios X de um padrão de calibração (CeO₂) e a emissão de luz de nanoaglomerados de ouro. É a parte da caracterização que já tem dados reais; a do óxido de grafeno do projeto aguarda o laboratório.",
      data: `${ni(X.n_frames)} quadros de um detector de área GE de ${X.shape[0]} × ${X.shape[1]} pixels e ${ni(U.n)} nanoaglomerados de ${ni(U.n_doi)} artigos.`,
      controls: [["Mostrar anéis ajustados", "Desenha sobre a imagem os círculos previstos pelo ajuste da geometria."]],
      take: `A geometria do difratômetro sai dos próprios dados: ${ni(X.geometry.n_rings)} anéis indexados, feixe de ${nf(X.geometry.energy_keV, 1)} keV, erro de ${nf(X.geometry.rms_residual_px, 2)} pixel.`,
    },
    sobre: {
      purpose: "De onde vem cada dado, o que é medida e o que é modelo, o que ainda depende das sínteses do projeto, glossário rápido e como reproduzir tudo.",
      data: "Os metadados de todas as bases (origem, DOI, licença, volume).",
      controls: [],
      take: "Tudo no site pode ser regerado com um comando e é conferido por testes automáticos.",
    },
  };

  /* ---------------------------------------------------------------------------------------------- figuras */
  const med = (a) => { const s = a.filter((x) => x != null && isFinite(x)).sort((p, q) => p - q); return s.length ? s[s.length >> 1] : NaN; };
  const R = L.records, sizeBy = (j) => med(R.size.filter((_, i) => R.red[i] === j)), nBy = (j) => R.red.filter((x) => x === j).length;
  const lam = (d) => { const c = O.lspr_curve, i = c.d.reduce((b, x, k) => (Math.abs(Math.log(x / d)) < Math.abs(Math.log(c.d[b] / d)) ? k : b), 0); return c.lambda[i]; };
  const er = E("redutor"), H2 = I.agnp.H2, h2max = Math.max(...H2.flat());
  const FIG = {
    /* visão geral */
    "ov-hero": { title: "Superfície 3D da abertura: extinção do ouro por Mie",
      what: "Uma \"paisagem\" calculada pela teoria de Mie: para cada combinação de comprimento de onda da luz (eixo λ) e diâmetro da partícula (eixo d), a altura diz quanta luz a partícula tira do feixe. A superfície é pintada com a cor que uma dispersão real daquele tamanho teria aos olhos.",
      read: ["Eixo λ (nm): a cor da luz, de 400 nm (violeta) a 900 nm (infravermelho próximo, invisível).", "Eixo log₁₀ d: o diâmetro em escala logarítmica (0,5 ≈ 3 nm; 1 = 10 nm; 2 = 100 nm).", "Altura: extinção normalizada; 1 é o máximo para aquele tamanho.", "A \"crista\" é o pico do plásmon (LSPR); arraste para girar e veja como ela anda."],
      example: `A crista fica em ~${nf(lam(10), 0)} nm para 10 nm, ~${nf(lam(20), 0)} nm para 20 nm e ~${nf(lam(80), 0)} nm para 80 nm: o ouro coloidal vai do vermelho-rubi ao púrpura e ao azul-acinzentado.`,
      caution: "É física calculada com constantes ópticas medidas, não uma medida da amostra; a validação contra medidas reais está na aba Óptica (Fig. 4.4c)." },
    "ov-strip": { title: "Faixa de cores do ouro coloidal",
      what: "A cor real de uma dispersão de ouro em água, em função do tamanho da partícula, calculada do espectro de Mie com colorimetria padrão.",
      read: ["Da esquerda para a direita o diâmetro cresce de 2 a 200 nm (escala log).", "Passe o mouse para ver o diâmetro e o código hexadecimal da cor.", "Todas as cores correspondem à MESMA massa de ouro: só o tamanho muda."],
      example: "Abaixo de ~3 nm: amarelo-amarronzado pálido (sem plásmon). De 5 a 50 nm: o vermelho-rubi clássico. Acima de ~60 nm: púrpura e, perto de 200 nm, cinza-azulado.",
      caution: "Cor calculada para luz do dia (iluminante D65), 1 cm de caminho óptico e o observador padrão CIE 1931; a foto de uma amostra real varia com a câmera e a iluminação." },
    "ov-find": { title: "Os oito achados",
      what: "Os oito resultados mais importantes do site, um por cartão, todos recalculados a partir dos dados a cada atualização.",
      read: ["Número grande: o resultado.", "Frase: o que ele significa, em uma linha.", "Rodapé: a seção da proposta (§) e o atalho para a análise completa."],
      example: `\"${nf(k.mie_median_abs_residual, 1)} nm\" = erro mediano do Mie ao prever o pico de absorção de ${ni(k.mie_validation_n)} esferas relatadas; \"R² ${nf(k.designer_cv_r2, 2)}\" = acerto do GP em validação cruzada.`,
      caution: "Um achado isolado pode enganar; cada cartão leva à análise com a incerteza e os testes." },
    "ov-check": { what: "A auditoria do site contra o que já é conhecido: cada linha confronta um resultado calculado aqui com um valor ou mecanismo estabelecido na literatura científica.",
      read: ["Primeira coluna: ícone de situação (verde = confere; amarelo = confere em parte).", "\"Verificação\": o que foi comparado.", "\"Resultado deste painel\" × \"Literatura\": os dois valores lado a lado, com a referência."],
      example: `A mediana da rota de Turkevich (${nf(V.turkevich.median, 1)} nm) cai na faixa clássica de 12–20 nm (Frens 1973: 16 nm); o efeito do NaBH₄ (×${nf(er.estimate, 2)}) cai na faixa esperada de 0,2–0,6.`,
      caution: "Concordar com a literatura não prova que está certo, mas discordar seria um sinal de alerta: é um teste de sanidade, não uma demonstração." },
    "ov-map": { title: "As 18 seções da proposta",
      what: "O mapa da proposta FAPESP: as 18 seções do plano de trabalho e em que aba do site cada uma aparece, com o estado de cada uma.",
      read: ["Verde: a seção já tem análise com dados experimentais.", "Amarelo (parcial): há dados reais, mas parte depende do laboratório.", "Cinza: depende das sínteses GO–AuNP do projeto.", "A barra acima soma os três estados; clique numa seção para abrir a aba."],
      example: "MISO (§4.8), campanha prospectiva (§4.11) e microscopia (§4.12) aguardam o laboratório; o restante já tem análise.",
      caution: "\"Experimental\" quer dizer que o método foi aplicado a dados reais, nem sempre aos dados GO–AuNP do projeto." },
    "ov-bench": { what: "Resumo do aprendizado ativo: para cada uma das cinco campanhas experimentais, quantos experimentos cada estratégia precisou (mediana de 40 repetições) até encontrar uma condição entre as 5 % melhores.",
      read: ["Cada linha é uma campanha; cada cor, uma estratégia (a legenda está no topo).", "Mais à esquerda = melhor (menos experimentos gastos).", "Compare sempre com o ponto do \"Aleatório\", a linha de base."],
      example: `AgNP: aleatório ${nf(v(() => ag.median_censored["Aleatório"]), 1)}, GP-EI ${nf(v(() => ag.median_censored["GP-EI"]), 1)} experimentos. Nas campanhas de ~100 condições (perovskitas, AutoAM) os pontos se misturam.`,
      caution: "Aqui quem não chegou conta como orçamento + 1, uma simplificação; a análise de sobrevivência da aba Aprendizado trata isso corretamente." },
    "ov-sources": { what: "O volume de cada base experimental usada no site.",
      read: ["Uma barra por base; o comprimento é o número de registros.", "Eixo em escala logarítmica: cada marca é 10× a anterior.", "Passe o mouse para ver o número exato."],
      example: `As bases da literatura têm milhares de registros (NSP 2026: ${ni(v(() => L.n_by_source["NSP 2026"]))}); as campanhas de laboratório autônomo, centenas a poucos milhares.`,
      caution: "Na escala log, uma barra duas vezes mais longa pode representar 100× mais registros." },

    /* literatura */
    "lit-3d": { what: "Cada ponto é uma síntese relatada que tem as três medidas ao mesmo tempo: temperatura de síntese, tamanho da partícula e pico de absorção.",
      read: ["Três eixos: temperatura (°C), tamanho (nm, escala log) e pico de absorção (nm).", "Cor = redutor principal: os três mais usados têm cor própria; o resto fica em cinza.", "Arraste para girar, role com o botão direito para mover.", "Clique num ponto: o quadro abaixo mostra o artigo, com link para o DOI."],
      example: `Com citrato a mediana de tamanho é ${nf(sizeBy(0), 1)} nm (${ni(nBy(0))} registros) e as sínteses se concentram perto de 100 °C (água fervente, protocolo de Turkevich); com NaBH₄ a mediana é ${nf(sizeBy(1), 1)} nm, em geral à temperatura ambiente.`,
      caution: "Os dados vêm de mineração automática de texto; os filtros físicos removem os erros grosseiros, mas um ponto isolado pode ser um erro de extração. Por isso existe o link para conferir no artigo." },
    "lit-hist": { what: "Quantas sínteses relatam cada tamanho, considerando os filtros escolhidos no topo da aba.",
      read: ["Eixo x: tamanho em escala log (3, 10, 30, 100 nm…), para caber de aglomerados a partículas grandes.", "Altura da barra: número de sínteses naquele intervalo.", "Mude os filtros (redutor, ligante…) e veja a distribuição se deslocar."],
      example: `Sem filtros, a mediana de todos os tamanhos relatados é ${nf(med(R.size), 1)} nm. Filtrando só NaBH₄, a distribuição anda para a esquerda; só CTAB, para a direita.`,
      caution: "Cada artigo pode contribuir com várias sínteses; artigos prolíficos pesam mais." },
    "lit-morph-bar": { what: "As oito formas de partícula mais relatadas na seleção atual.",
      read: ["Barra horizontal maior = forma mais comum.", "Mude os filtros para ver que reagentes levam a que formas."],
      example: "Esferas dominam em quase toda seleção; escolhendo o ligante CTAB, bastões e outras formas não esféricas ganham peso (o CTAB adsorve em faces específicas do cristal; aba Causalidade).",
      caution: "A forma é a relatada pelos autores e extraída do texto; \"partícula\" sem qualificação é tratada como esférica nas análises." },
    "lit-years": { what: "Como a preferência por cada redutor mudou ao longo dos anos de publicação.",
      read: ["Uma linha por redutor; eixo y: porcentagem das sínteses publicadas naquele ano que usam o redutor.", "Só anos com pelo menos 40 sínteses (com poucas, a porcentagem oscila por acaso).", "Passe o mouse para ver quantas sínteses tem o ano."],
      example: "Serve à §4.14 (sustentabilidade): a troca entre redutores mais brandos (citrato, ácido ascórbico) e mais agressivos (NaBH₄) ao longo do tempo indica para onde a área caminha.",
      caution: "Só a base de Cruse et al. tem o ano de forma consistente; tendência na literatura não é o mesmo que melhor prática." },
    "go-tbl": { what: "Os registros que mencionam óxido de grafeno: o ponto de partida da curadoria específica do projeto (GO–AuNP).",
      read: ["Uma linha por síntese: ano, artigo/DOI, redutores, suporte, morfologia, tamanho e temperatura.", "A caixa de busca filtra por qualquer texto (redutor, suporte, DOI).", "O DOI é um link para o artigo original."],
      example: `${ni(L.n_go)} registros de ${ni(L.n_go_doi)} artigos mencionam GO.`,
      caution: "Mencionar GO não garante que o ouro foi crescido sobre o GO; cada artigo precisa ser lido antes de entrar na base do projeto." },

    /* óptica */
    "op-spec": { what: "O espectro de absorção (extinção por comprimento de onda) previsto por Mie para as partículas escolhidas nos controles, sobreposto ao espectro-alvo do projeto.",
      read: ["Linha tracejada escura: o alvo (AuNP de 20 nm, dispersão de 8 %).", "Linha azul: o espectro previsto para a sua escolha.", "Área sombreada: a diferença entre os dois na faixa avaliada, que vira a perda J.", "Normalização \"por volume\" mostra quanto cada tamanho absorve com a mesma massa de ouro."],
      example: "Nos valores do alvo as curvas coincidem e J ≈ 0. Com 45 nm o pico anda para a direita, a curva se separa do alvo e J passa de 10.",
      caution: "J compara a FORMA do espectro (normalizada pelo máximo), não a concentração; duas amostras de mesma forma e intensidades diferentes têm o mesmo J." },
    "op-cuv": { title: "Cubeta: a cor prevista da dispersão",
      what: "A cor que a dispersão teria numa cubeta de 1 cm, calculada do espectro previsto.",
      read: ["Muda com diâmetro e dispersão (que mudam o espectro) e com a concentração (A₀, que muda a intensidade).", "O texto ao lado explica a cor e mostra o código hexadecimal."],
      example: "20 nm: o vermelho-rubi clássico; 90 nm: púrpura; abaixo de 3 nm: marrom-amarelado pálido.",
      caution: "Cor calculada (Mie + colorimetria CIE 1931 sob luz D65), não fotografada." },
    "op-surf": { what: "A extinção para todos os comprimentos de onda e diâmetros (a mesma superfície da abertura), com uma linha vermelha marcando o diâmetro escolhido no controle.",
      read: ["Eixos: λ (nm), log₁₀ do diâmetro e extinção normalizada.", "A linha vermelha é exatamente o espectro do gráfico ao lado.", "Gire para ver a crista do plásmon se deslocar."],
      example: `Ao arrastar o diâmetro de 10 para 80 nm, a linha sobe a crista e o pico vai de ~${nf(lam(10), 0)} para ~${nf(lam(80), 0)} nm.`,
      caution: "Cada linha do diâmetro está normalizada pelo próprio máximo: a altura não compara intensidades entre tamanhos." },
    "op-valid": { what: "O teste mais importante da física do site: o pico de absorção RELATADO contra o tamanho relatado, para esferas da literatura, com a curva de Mie por cima.",
      read: ["Pontos: um registro cada (cor = base de origem); passe o mouse para ver o artigo.", "Linha preta: Mie sem nenhum ajuste; tracejada: curva empírica de Haiss et al. (2007).", "Eixo x em escala log; quanto mais perto da linha, melhor a física descreve o relato."],
      example: `Erro mediano de ${nf(O.lit_spheres.median_abs_residual, 1)} nm; ${nf(100 * O.lit_spheres.within_5nm, 0)} % dos ${ni(O.lit_spheres.n)} relatos ficam a até 5 nm da previsão, sem nenhum parâmetro ajustado.`,
      caution: "A nuvem em torno da curva é o erro dos RELATOS (pico lido à mão, tamanho de outra técnica ou de outra síntese do artigo), não falha da física." },
    "op-J": { what: "A perda J (em escala log₁₀) para todas as combinações de diâmetro e dispersão: o mapa de onde a síntese precisa cair para atender ao alvo.",
      read: ["Vale (cores escuras, baixo) = perto do alvo; montanha = longe.", "Eixos: log₁₀ do diâmetro e dispersão σ.", "O ponto vermelho é a escolha atual dos controles; mova-os e veja o ponto andar."],
      example: "O vale é estreito no diâmetro e largo na dispersão: errar o tamanho em 30 % custa muito mais do que errar a uniformidade em 30 %. Para o projeto, controlar o tamanho é prioridade.",
      caution: "log₁₀ J = 0 corresponde a J = 1, o limite do rascunho do pré-registro." },
    "op-inv": { what: "A pergunta ao contrário: medi um pico de absorção; que tamanhos de partícula são compatíveis com ele? A resposta é uma distribuição de probabilidade, obtida pela regra de Bayes.",
      read: ["Pontilhado cinza: a priori (tamanhos comuns na literatura).", "Tracejado laranja: verossimilhança (o que o pico sozinho diz, com o erro real dos relatos).", "Área azul: posterior (a combinação dos dois); faixa dourada: intervalo de credibilidade de 90 %.", "Mova o controle do pico e alterne a a priori para ver o efeito de cada parte."],
      example: `Com o pico em 520 nm o tamanho fica entre ~4 e ~30 nm. O intervalo de 90 % acertou o tamanho real em ${nf(100 * O.inversion.coverage90, 0)} % dos artigos de teste (a verossimilhança t de Student com ν = ${O.inversion.nu} foi escolhida por isso; a gaussiana acertava só ${nf(100 * O.inversion.scan[0].coverage90, 0)} %).`,
      caution: "Pico perto de 520 nm não distingue 5 de 25 nm. É por isso que o projeto confirma o tamanho por microscopia eletrônica (TEM) e usa o espectro inteiro (perda J) em vez do pico sozinho." },
    "op-haiss": { what: "A conferência com uma curva empírica muito usada (Haiss et al., Anal. Chem. 2007), que liga o pico ao tamanho entre 25 e 100 nm.",
      read: ["Linha contínua: Mie deste painel; tracejada: a curva de Haiss.", "Se as duas coincidem, a física do painel concorda com a calibração experimental clássica."],
      example: `As duas diferem no máximo ${nf(O.haiss.max_abs_diff, 1)} nm entre 25 e 100 nm; para 20 nm o Mie dá ${nf(O.haiss.mie_20nm, 0)} nm (o valor de referência é ~520 nm).`,
      caution: "A curva de Haiss não vale abaixo de 25 nm, onde o pico quase não muda." },
    "op-neff": { what: "Um teste de uma possível melhoria: e se o meio em volta da partícula tivesse índice de refração maior que o da água (por causa da camada de ligante adsorvida)?",
      read: ["Cada linha é um índice testado (1,333 = água).", "\"Ajuste\": erro na metade dos artigos usada para escolher; \"validação\": erro na outra metade, que decide.", "\"Viés\": se o Mie fica sistematicamente à esquerda ou à direita; \"máx. |Mie − Haiss|\": quanto se afasta da curva clássica.", "Em negrito, o melhor na validação."],
      example: "O melhor índice ganha só décimos de nanômetro na validação e se afasta da curva de Haiss; por isso o painel continua com a água, sem ajuste.",
      caution: "Ajustar um parâmetro e avaliar nos mesmos dados sempre melhora; só a validação em dados separados (outros artigos) conta." },
    "op-bins": { what: "O erro do Mie (pico relatado − pico previsto) separado por faixa de tamanho, para saber onde a física acerta mais e onde os relatos se desviam.",
      read: ["Registros: quantos relatos há na faixa.", "Resíduo mediano: positivo = o relato fica à direita (mais vermelho) do previsto.", "Desvio absoluto mediano: o tamanho típico do erro na faixa."],
      example: "Entre 20 e 80 nm os relatos ficam alguns nanômetros à direita do Mie: compatível com agregação parcial, meio com índice maior ou tamanho subestimado pela microscopia.",
      caution: "Acima de 80 nm há poucos registros e o erro típico cresce muito." },

    /* designer */
    "ds-surf": { what: "O que o GP espera da perda espectral (quanto o espectro se afasta do alvo) ao variar duas vazões ao mesmo tempo, com as outras três fixas nos valores dos controles.",
      read: ["Superfície: previsão do GP, incerteza ou EI, conforme o seletor \"Superfície\".", "Escolha nos seletores quais duas vazões vão nos eixos.", "Pontos vermelhos: condições medidas perto deste corte; cinza: as demais (altura = perda média medida).", "Gire com o mouse; vales = regiões promissoras."],
      example: `A melhor condição medida tem perda ${nf(D.best_measured.loss, 3)}; os vales da superfície mostram onde o GP espera perdas parecidas ou menores.`,
      caution: "É um corte de um espaço de 5 dimensões: mudar as outras três vazões muda a superfície inteira." },
    "ds-cv": { what: "O teste honesto do GP: cada condição foi prevista por um modelo treinado sem ela (validação cruzada em 10 dobras, com os hiperparâmetros reajustados em cada dobra).",
      read: ["Eixo x: o previsto; eixo y: o medido (ambos em ln da perda).", "Pontos sobre a diagonal = previsão perfeita.", "Barras horizontais = intervalo de 95 % do GP para aquela condição."],
      example: `R² = ${nf(D.cv.r2, 2)}: o modelo explica ${nf(100 * D.cv.r2, 0)} % da variação das medidas; ${nf(100 * D.cv.coverage95, 0)} % das medidas caem dentro da barra de 95 % (o ideal é 95 %).`,
      caution: "Pontos longe da diagonal com barras curtas seriam preocupantes (o modelo errou e estava confiante); o gráfico de calibração investiga isso." },
    "ds-pd": { what: "Como a perda prevista muda quando só UMA vazão varia e as outras quatro ficam nos valores dos controles.",
      read: ["Um painel por vazão, todos na mesma escala vertical.", "Linha: previsão; faixa: intervalo de 95 %.", "Ponto vermelho: o valor atual daquela vazão."],
      example: "Uma curva em U indica um ótimo intermediário; uma curva quase plana, uma vazão que pouco importa naquele ponto (como o PVA); uma faixa larga, pouca informação naquela região.",
      caution: "É o efeito \"um de cada vez\": interações entre vazões aparecem melhor na aba Interpretabilidade (H² e Sobol)." },
    "ds-models": { what: "A comparação entre cinco versões do modelo nas mesmas 10 dobras, para justificar a escolha do GP usado no site.",
      read: ["R² e RMSE: acerto da previsão.", "Cobertura: a fração das medidas dentro do IC 95 % (ideal: 95 %).", "NLPD: nota que pune ao mesmo tempo erro e incerteza mal calibrada (menor é melhor; critério fixado antes)."],
      example: "Os quatro núcleos empatam (diferença menor que 0,05 em NLPD), então fica o Matérn-5/2 da proposta. Usar o ruído medido das réplicas piora muito: o erro vem de algo que as vazões não descrevem (dia, lote, temperatura do chip).",
      caution: "Escolher o modelo olhando só o R² ignoraria se a incerteza é honesta; por isso o critério é o NLPD." },
    "ds-rel": { what: "Os intervalos do GP dizem a verdade? Para cada nível nominal (10 %, 20 %… 99 %), a fração das medidas fora da dobra que caiu dentro do intervalo correspondente.",
      read: ["Diagonal pontilhada = calibração perfeita.", "Acima da diagonal: intervalos largos demais (conservadores); abaixo: estreitos demais (otimistas).", "Tracejado: referência com uma incerteza constante para todas as condições."],
      example: `O nível nominal de 50 % cobre ${nf(100 * D.calibration.coverage[4], 0)} % e o de 99 % cobre ${nf(100 * D.calibration.coverage[D.calibration.coverage.length - 1], 0)} %: intervalos um pouco largos no centro e caudas um pouco curtas.`,
      caution: "Uma curva sobre a diagonal não garante que a incerteza de CADA condição seja informativa: o CRPS (texto ao lado) mostra que ela não supera uma incerteza constante." },
    "ds-pit": { what: "Outra forma de ver a calibração: em que posição da distribuição prevista caiu cada medida real (o valor PIT, entre 0 e 1).",
      read: ["Histograma plano (na linha pontilhada) = calibrado.", "Corcova no meio = intervalos largos demais.", "Picos nas pontas = caudas curtas demais (surpresas frequentes)."],
      example: `Teste de Kolmogorov–Smirnov contra o histograma plano: ${pf(D.calibration.pit_ks_p)}, ou seja, os dados não rejeitam a calibração; desvio dos resíduos padronizados ${nf(D.calibration.z_sd, 2)} (ideal 1).`,
      caution: "Com 164 condições, um histograma de 10 barras oscila naturalmente alguns pontos." },
    "ds-sugg": { what: "As cinco condições que o GP sugere testar a seguir: as de maior melhoria esperada (EI), afastadas entre si para não gastar experimentos no mesmo lugar.",
      read: ["Colunas: as cinco vazões da condição, a perda prevista, o IC 95 % e a EI.", "\"Carregar\" leva a condição aos controles do topo para examiná-la."],
      example: `A primeira sugestão tem perda prevista ${nf(D.suggestions[0].pred_loss, 3)} (IC ${nf(D.suggestions[0].lo, 3)}–${nf(D.suggestions[0].hi, 3)}); a melhor medida até agora tem ${nf(D.best_measured.loss, 3)}.`,
      caution: "EI equilibra explorar (onde há incerteza) e aproveitar (onde a previsão é boa); uma sugestão não é uma promessa de resultado." },

    /* preditor */
    "pr-forest": { what: "O tamanho previsto para a receita montada no formulário, ao lado do que as receitas publicadas iguais ou parecidas relatam.",
      read: ["Primeira linha (vermelha): a previsão; traço grosso = 50 % dos casos, fino = 90 %, círculo = mediana.", "Linhas azuis: receitas publicadas (idêntica primeiro, depois as mais parecidas); barra = 10–90 % dos relatos; ponto maior = mais sínteses.", "Faixa dourada: o alvo ± 20 %.", "Eixo x em escala log."],
      example: "Com a receita de Turkevich (citrato, 100 °C), a previsão (~17 nm) bate com as 2 461 sínteses idênticas publicadas (mediana 16 nm).",
      caution: "Se a receita idêntica publicada discordar muito da previsão, o texto ao lado avisa: o modelo suaviza combinações raras de reagentes, e nesse caso o relato direto é mais confiável." },
    "pr-cuv": { what: "A cor da dispersão e o pico de absorção esperados para o tamanho mediano previsto (teoria de Mie, mesma conta da aba Óptica).",
      read: ["Cubeta: a cor; número grande: o pico (LSPR) em nm.", "O texto abaixo dá o pico para a faixa de 50 % e alertas para formas não esféricas."],
      example: "17 nm → pico em ~522 nm, vermelho-rubi.", caution: "Vale para esferas; bastões têm um segundo pico no vermelho/infravermelho próximo que este cálculo não inclui." },
    "pr-whatif": { what: "Se você mudasse UM item da receita, quanto subiria ou cairia a chance de acertar o alvo ± 20 %?",
      read: ["Barra verde para a direita = a mudança AUMENTA a chance; laranja para a esquerda = diminui.", "Valores em pontos percentuais (de 22 % para 30 % = +8 pontos).", "Mostra as dez trocas de maior efeito: incluir ou tirar um reagente, mudar a rota, a forma ou a temperatura."],
      example: "Partindo de Turkevich com alvo de 20 nm, acrescentar CTAB aumenta a chance e acrescentar THPC (um redutor forte) diminui: THPC faz partículas pequenas.",
      caution: "É associação na literatura (quem usa X relata Y), não causa; os efeitos causais, corrigidos por confundidores, estão na aba Causalidade." },
    "pr-temp": { what: "A mesma receita em temperaturas de 0 a 300 °C: como o tamanho previsto muda com a temperatura de síntese.",
      read: ["Linha: mediana prevista; faixas: 50 % e 90 %.", "Eixo y em escala log.", "Ponto vermelho: a temperatura escolhida no formulário."],
      example: "Degraus na curva aparecem onde há grupos de artigos com protocolos diferentes naquela temperatura (por exemplo, a água fervente a 100 °C).",
      caution: "Fora da faixa de temperaturas usada com aquela receita, o modelo extrapola: a curva fica plana, não porque a química é plana." },
    "pr-inv": { what: "Design inverso: em vez de \"dada a receita, qual o tamanho?\", pergunta \"dado o tamanho que eu quero, qual receita?\".",
      read: ["Receitas publicadas com pelo menos 5 sínteses, avaliadas em 25, 60 e 100 °C (fica a melhor temperatura de cada uma).", "Ordenadas pela probabilidade prevista de cair no alvo ± 20 %.", "\"Relatado\" mostra o que a literatura obteve com aquela receita; \"Carregar\" coloca a receita no formulário."],
      example: "Para um alvo de 3 nm aparecem NaBH₄ + TOAB/tiol (a rota de Brust, conhecida por partículas de 1–3 nm), como a química prevê.",
      caution: "Só receitas já publicadas entram: evita sugerir algo que o modelo nunca viu. Mesmo a melhor tem chance moderada, porque o tamanho depende de detalhes que os artigos não registram." },
    "pr-tbl": { what: "As receitas publicadas mais parecidas com a sua, com exemplos clicáveis.",
      read: ["Primeira coluna: a diferença para a sua receita (\"+ PVP\" = elas têm PVP e a sua não; \"− citrato\" = elas não têm citrato).", "Sínteses e artigos: quantos relatos há.", "Mediana e faixa de 10–90 % dos tamanhos relatados; exemplos com link para o DOI."],
      example: "Para Turkevich, as vizinhas mostram o efeito de mudar a forma ou de usar sementes sobre o tamanho relatado.",
      caution: "Semelhança é medida pelos reagentes (Jaccard), rota e forma; razões molares e pH não estão nas bases." },
    "pr-val": { what: "A prova de que os intervalos do Preditor são honestos.",
      read: ["Nominal: a cobertura prometida (50 % ou 90 %).", "Sem conformal: a cobertura do modelo de quantis cru.", "Conformal (registros e artigos novos): a cobertura medida em artigos que o modelo nunca viu; a de artigos deve bater com a nominal.", "Largura típica: o fator entre o limite superior e o inferior."],
      example: `90 % prometido → ${nf(100 * P.bands["90"].coverage_articles, 1)} % obtido em artigos novos; 50 % → ${nf(100 * P.bands["50"].coverage_articles, 1)} %. A largura típica do intervalo de 90 % é um fator ×${nf(P.bands["90"].median_fold_width, 0)}.`,
      caution: "A garantia vale \"em média\" sobre artigos; para uma receita específica e rara a cobertura pode ser pior." },

    /* aprendizado */
    "bo-curves": { what: "O melhor resultado encontrado até cada experimento, para cada estratégia: quem chega mais rápido ao topo.",
      read: ["Eixo y: 0 = pior condição da base, 1 = a melhor (resultados normalizados para comparar campanhas).", "Linha = mediana das 40 repetições; faixa = quartis (a metade central das repetições).", "Curva que sobe mais cedo = estratégia mais eficiente; clique na legenda para esconder uma estratégia."],
      example: "No AgNP o GP-EI chega perto de 1 em ~15 experimentos, enquanto o sorteio precisa de bem mais.",
      caution: "As primeiras 5 condições são sorteadas e iguais para todas as estratégias; diferenças aparecem só depois delas." },
    "bo-reach": { what: "Quantos experimentos cada repetição precisou para achar uma condição do top 5 %, por estratégia.",
      read: ["Cada ponto é uma das 40 repetições; caixa = quartis; traço = mediana.", "Pontos acima da linha horizontal não chegaram dentro do orçamento.", "Caixa mais baixa e mais estreita = estratégia mais rápida e mais previsível."],
      example: `No AgNP todas as estratégias chegaram em todas as repetições (fração ${nf(100 * v(() => ag.reach_top5["GP-EI"].fraction), 0)} % para o GP-EI); a diferença está em quão cedo.`,
      caution: "Repetições que chegam no experimento 1 tiveram a sorte de já sortear uma condição do top 5 % na partida." },
    "bo-pair": { what: "A comparação justa: em cada repetição as duas estratégias partem das mesmas 5 condições sorteadas, então a diferença entre elas não é sorte de partida.",
      read: ["Uma barra por repetição: experimentos da estratégia − experimentos do aleatório.", "Barra para baixo (verde) = a estratégia chegou antes; para cima (laranja) = o sorteio chegou antes.", "O rótulo traz o p-valor do teste de Wilcoxon pareado."],
      example: `No AgNP o GP-EI venceu ${v(() => ag.paired["GP-EI"].wins)} das ${B.seeds} repetições, empatou ${v(() => ag.paired["GP-EI"].ties)} e perdeu ${v(() => ag.paired["GP-EI"].losses)}.`,
      caution: "Empates acontecem quando as duas acham o top 5 % na própria partida." },
    "bo-insight": { what: "Como cada estratégia escolhe o próximo experimento, e a leitura dos resultados do benchmark.",
      read: ["Aleatório: sorteia a próxima condição (linha de base).", "GP-EI: processo gaussiano + melhoria esperada (o Designer).", "GP-UCB: GP + \"otimismo diante da incerteza\" (média + 2 desvios).", "RF-EI: floresta aleatória + melhoria esperada."],
      example: "O ganho dos métodos com modelo aparece nos espaços grandes; com ~100 condições, o top 5 % tem só 5 condições e a partida aleatória já cobre boa parte dele.",
      caution: "O resultado é o mesmo de Liang et al. (2021), de onde vêm quatro das bases: não é garantido que o GP ganhe sempre, e por isso o projeto compara braços." },
    "bo-km": { what: "Análise de sobrevivência: a fração das repetições que AINDA NÃO achou o top 5 % depois de t experimentos (curva de Kaplan–Meier). O exemplo interativo na seção de conceitos mostra a curva se formando passo a passo.",
      read: ["A curva começa em 100 % e desce um degrau a cada repetição que chega ao top 5 %.", "Curva que cai mais rápido = estratégia melhor.", "Faixa = intervalo de 95 % (Greenwood).", "RMST na legenda = número médio de experimentos gastos até chegar (a área sob a curva)."],
      example: `No AgNP, RMST de ${nf(v(() => ag.survival.rmst["Aleatório"]), 1)} experimentos para o aleatório contra ${nf(v(() => ag.survival.rmst["GP-EI"]), 1)} para o GP-EI.`,
      caution: "Repetições que não chegam são \"censuradas\": sabemos só que levariam mais que o orçamento, e a curva usa exatamente essa informação, sem inventar quando chegariam." },
    "bo-rmst": { what: "Quantos experimentos cada estratégia economiza em relação ao sorteio, em cada campanha, com incerteza.",
      read: ["Ponto à direita do zero = economiza experimentos; à esquerda = gasta mais.", "Barra = IC 95 % por bootstrap das repetições.", "Rótulo P = probabilidade de a estratégia ser melhor (bootstrap bayesiano).", "Cor: verde = IC inteiro acima de zero; cinza = incerto."],
      example: `GP-EI no AgNP: economiza ${nf(-agS.rmst_diff, 1)} experimentos (IC ${nf(-v(() => agS.ci95[1]), 1)}–${nf(-v(() => agS.ci95[0]), 1)}), P = ${nf(agS.p_better, 2)}.`,
      caution: "Economizar 5 experimentos numa campanha de 60 é muito; numa de 1000 seria pouco: leia junto com o tamanho da campanha." },
    "bo-surv": { what: "A tabela completa da análise de sobrevivência, em todas as campanhas e estratégias.",
      read: ["RMST do aleatório: a referência.", "Para cada estratégia: economia em experimentos (IC 95 %), P(melhor) e o p do teste log-rank.", "Negrito = IC inteiro acima de zero."],
      example: `No AgNP o log-rank do GP-EI dá ${pf(agS.logrank_p)}.`,
      caution: "O log-rank ignora o pareamento das repetições; é mais conservador que o bootstrap pareado." },
    "bo-tbl": { what: "O resumo clássico do benchmark: a mediana de experimentos até o top 5 % e o teste pareado contra o aleatório.",
      read: ["Uma linha por campanha; uma coluna por estratégia.", "Entre parênteses: vitórias–empates–derrotas, p de Wilcoxon e p corrigido por Holm.", "Negrito = significativo depois da correção para as 15 comparações."],
      example: `Só o AgNP resiste à correção de Holm (GP-EI p_Holm = ${nf(v(() => ag.paired["GP-EI"].p_holm), 3)}); crossed barrel e P3HT/CNT ficam como evidência sugestiva.`,
      caution: "Com 15 testes, alguns dão p < 0,05 por acaso; Holm corrige isso (veja o exemplo interativo de p-valores)." },

    /* interpretabilidade */
    "sh-bees": { what: "O \"enxame\" SHAP: quanto cada variável empurrou a previsão de cada síntese para cima ou para baixo.",
      read: ["Cada ponto é uma síntese; uma linha por variável, as mais importantes no topo.", "À direita do zero: a variável aumentou o alvo naquela síntese; à esquerda: diminuiu.", "Cor: o valor da variável (claro = baixo, escuro = alto).", "Escolha o modelo no seletor: AgNP, nanoaglomerados ou literatura."],
      example: "Se os pontos escuros de uma variável ficam à direita, valores altos dela aumentam o alvo; pontos espalhados dos dois lados indicam efeito que depende das outras variáveis.",
      caution: "SHAP explica o MODELO, não a natureza: vale tanto quanto o modelo vale (veja o R² no topo)." },
    "sh-bar": { what: "A importância média de cada variável: a média do tamanho das contribuições SHAP sobre todas as sínteses.",
      read: ["Barra maior = variável que mais move o alvo, em média.", "Não diz a direção (para isso, o enxame ao lado)."],
      example: `No GP AgNP a primeira barra é ${esc(I.agnp.features[I.agnp.values[0].map((_, j) => j).reduce((b, j) => (I.agnp.values.reduce((a, r) => a + Math.abs(r[j] || 0), 0) > I.agnp.values.reduce((a, r) => a + Math.abs(r[b] || 0), 0) ? j : b), 0)])}.`,
      caution: "Importância alta não quer dizer efeito causal; variáveis correlacionadas dividem a importância entre si." },
    "sh-dep": { what: "Como a contribuição de UMA variável muda com o valor dela (escolha a variável no seletor).",
      read: ["Eixo x: valor da variável; eixo y: a contribuição SHAP dela.", "Cor: a variável que mais interage com ela (no AgNP, pela estatística H²).", "Uma nuvem em faixa larga num mesmo x indica interação."],
      example: "No AgNP, a contribuição das sementes muda de sinal ao longo da faixa: efeito não linear (pouca e muita semente fazem coisas diferentes).",
      caution: "" },
    "sh-h2": { what: "As interações entre pares de vazões no GP AgNP, medidas pela estatística H² de Friedman.",
      read: ["Cada célula: a fração do efeito conjunto do par que não se explica pelos efeitos separados.", "0 = sem interação; mais escuro = interação maior.", "A matriz é simétrica; a diagonal fica vazia."],
      example: `O par AgNO₃ × citrato é o de maior interação (H² = ${nf(h2max, 2)}): o efeito do AgNO₃ depende de quanto citrato há.`,
      caution: "H² é calculado sobre a previsão do GP, não sobre medidas diretas." },
    "sh-sobol": { what: "Sensibilidade global: que fração da variação total da previsão cada vazão explica sozinha (S1) e incluindo as interações (ST).",
      read: ["Azul: S1 (efeito sozinho); laranja: ST (total, com interações); barras = IC 95 %.", "ST − S1 grande = a variável age em combinação com outras.", "ST ≈ 0 = a variável pode ser fixada sem perder nada."],
      example: `AgNO₃: S1 = ${nf(I.agnp.sobol.S1[0], 2)}, ST = ${nf(I.agnp.sobol.ST[0], 2)}; as vazões explicam sozinhas ${nf(100 * I.agnp.sobol.sum_S1, 0)} % da variação e o resto vem de interações. PVA e vazão total têm ST ≈ 0.`,
      caution: "Os índices supõem as vazões variando de forma independente em toda a faixa medida." },

    /* variabilidade */
    "va-noise": { what: "O ruído de repetir a mesma síntese: o desvio entre réplicas contra a perda média, para cada uma das 164 condições da campanha AgNP.",
      read: ["Cada ponto é uma condição; ponto maior = mais réplicas.", "Eixo x: perda média da condição; eixo y: desvio padrão entre as réplicas.", "Se o ruído fosse igual em todo lugar, os pontos formariam uma faixa horizontal."],
      example: `O desvio muda de condição para condição (teste de Brown–Forsythe ${pf(V.agnp.levene_p)}); ${nf(100 * V.agnp.icc, 0)} % da variação total é entre condições (ICC) e só o resto é ruído de réplica.`,
      caution: "Ruído de réplica é diferente de variação entre laboratórios (gráficos ao lado)." },
    "va-3d": { what: "Onde a síntese é menos repetível: o coeficiente de variação (desvio ÷ média) das réplicas no espaço de três vazões.",
      read: ["Cada ponto é uma condição; cor mais escura = menos repetível.", "Eixos: três das vazões da campanha.", "Gire para ver de vários ângulos."],
      example: `CV mediano das réplicas: ${nf(100 * V.agnp.median_cv, 1)} %. Pontos escuros agrupados indicam regiões instáveis da receita.`,
      caution: "" },
    "va-turk": { what: "A mesma receita clássica (Turkevich: citrato como único redutor, sem sementes, esferas) relatada em centenas de artigos, um tamanho por artigo.",
      read: ["Histograma em escala log.", "Linha cheia: mediana; pontilhadas: 10 % e 90 % (80 % dos artigos ficam entre elas).", "Passe o mouse para ver quantos artigos há em cada faixa."],
      example: `Mediana ${nf(V.turkevich.median, 1)} nm (Frens 1973: 16 nm); 80 % dos ${ni(V.turkevich.n_papers)} artigos entre ${nf(V.turkevich.q10_q90[0], 0)} e ${nf(V.turkevich.q10_q90[1], 0)} nm; ${nf(100 * V.turkevich.frac_10_20nm, 0)} % entre 10 e 20 nm.`,
      caution: "Parte da largura é intencional: variar a razão citrato:ouro muda o tamanho de 16 a 147 nm (Frens 1973); o resto é a variabilidade entre fontes." },
    "va-gen": { what: "Prever para uma síntese nova de um artigo já visto é muito mais fácil do que prever para um artigo nunca visto: o \"contexto da fonte\" pesa.",
      read: ["Eixo x: emissão medida dos nanoaglomerados; eixo y: prevista.", "Azul: validação aleatória (síntese nova); laranja: validação por artigo (artigo novo).", "Diagonal = acerto."],
      example: `R² ${nf(V.aunc_generalization.r2_random, 2)} para síntese nova contra ${nf(V.aunc_generalization.r2_new_paper, 2)} para artigo novo.`,
      caution: "É a premissa do projeto em números: o que o artigo (o laboratório, o lote) não registra decide boa parte do resultado." },

    /* causal */
    "ca-dag": { title: "Grafo causal mecanístico",
      what: "O mapa de causas e efeitos da síntese, desenhado a partir da química conhecida (nucleação e crescimento de LaMer, Turkevich–Frens, Brust, sementes).",
      read: ["Seta = \"causa\"; rótulo da seta = o mecanismo.", "Setas vermelhas: caminhos cujo efeito foi estimado com dados (com o valor).", "Caixa tracejada: variável latente, que não é medida (a nucleação)."],
      example: "Força do redutor → nucleação → tamanho: redutor forte cria muitos núcleos de uma vez e as partículas ficam pequenas.",
      caution: "O grafo vem da teoria, não dos dados; os dados testam as setas vermelhas." },
    "ca-forest": { what: "Os quatro efeitos causais estimados, comparados com a faixa que a literatura prevê.",
      read: ["Ponto = estimativa (AIPW); barra = IC 95 % por bootstrap de artigos.", "Faixa dourada = faixa esperada pela química.", "1 = nenhum efeito; abaixo de 1 = diminui; acima = aumenta (escala log).", "Ponto cheio = robusto a todos os estimadores; vazado = magnitude frágil."],
      example: `NaBH₄ × citrato: as partículas ficam ×${nf(er.estimate, 2)} do tamanho (IC ${nf(v(() => er.estimate_ci95[0]), 2)}–${nf(v(() => er.estimate_ci95[1]), 2)}), dentro da faixa esperada de 0,2–0,6.`,
      caution: "Para tamanho a escala é razão de médias geométricas; para forma, razão de riscos (quantas vezes mais provável)." },
    "ca-verdicts": { what: "O veredito de cada efeito: direção, magnitude, robustez e a explicação química, com a referência.",
      read: ["Selo verde = confirma a literatura; amarelo = confirma a direção, magnitude frágil.", "Primeira linha: estimativa, IC e população usada.", "Última linha: o que o modelo preditivo (SHAP) diz do mesmo reagente."],
      example: "Os quatro efeitos confirmam a direção prevista; o do tiol tem magnitude frágil (poucos registros comparáveis).",
      caution: "Quando o modelo preditivo e o causal discordam, a associação condicional está enganando: vale o causal." },
    "ca-rep": { what: "Replicação: o mesmo efeito estimado separadamente em duas bases independentes (extrações e artigos diferentes) e o resultado combinado.",
      read: ["Azul: Cruse 2022; amarelo: NSP 2026; losango vermelho: combinado por efeitos aleatórios.", "Barras = IC 95 %; linha pontilhada = nenhum efeito.", "I² no texto: quanto da diferença entre bases não é acaso."],
      example: "Os quatro efeitos têm a mesma direção nas duas bases; o NSP dá efeitos mais fortes em todos, como esperado quando o Cruse dá um tamanho só por artigo (o que dilui o contraste).",
      caution: "Com só duas bases, o intervalo combinado fica largo: é o preço honesto da heterogeneidade." },
    "ca-est": { what: "O mesmo efeito calculado por métodos diferentes (escolha o efeito no seletor acima); se concordam, o resultado é robusto.",
      read: ["AIPW: o principal (duplamente robusto).", "IPW e balanceamento por entropia: só com pesos.", "Aparo 5–95 %: tirando as sínteses com escore extremo.", "\"Sem ajuste\": a comparação ingênua, para referência."],
      example: `NaBH₄: sem ajuste ×${nf(er.naive_ratio, 2)}, AIPW ×${nf(er.ratio, 2)}, IPW ×${nf(er.ipw_ratio, 2)}, entropia ×${nf(er.ebal_ratio, 2)}.`,
      caution: "Concordância entre estimadores protege contra erros de modelagem, não contra confundidores não medidos (para isso, o E-value)." },
    "ca-smd": { what: "O ajuste equilibrou os grupos? A diferença padronizada (SMD) de cada covariável entre tratados e controles, antes e depois dos pesos.",
      read: ["Cada linha é uma covariável (base, ano, temperatura, outros reagentes…).", "Laranja: antes do ajuste; azul e verde: depois (IPW e entropia).", "Faixa sombreada = |SMD| < 0,1, o equilíbrio aceitável."],
      example: `Para o NaBH₄, o maior desequilíbrio antes era ${nf(Math.max(...er.smd_before.map(Math.abs)), 2)}; depois do balanceamento por entropia, ${nf(Math.max(...er.smd_ebal.map(Math.abs)), 3)}.`,
      caution: "Equilibrar as covariáveis medidas não equilibra as não medidas." },
    "ca-ps": { what: "Os grupos são comparáveis? A distribuição do escore de propensão (a chance de receber o tratamento dadas as covariáveis) nos tratados e nos controles.",
      read: ["Dois histogramas sobrepostos: tratados e controles.", "As distribuições precisam se sobrepor: sem sobreposição não há com quem comparar.", "Os pesos usam escores aparados em [0,02; 0,98] para evitar pesos explosivos."],
      example: "Quando quase só os tratados têm escores perto de 1, aquela região não tem controles comparáveis e o efeito ali é extrapolado.",
      caution: "" },
    "ca-chain": { what: "Teste de coerência da cadeia NaBH₄ → tamanho → pico: o efeito do NaBH₄ no pico de absorção é o que a física (Mie) prevê a partir do efeito no tamanho?",
      read: ["Ponto vermelho: efeito observado no pico, com IC 95 %.", "Ponto azul: o deslocamento previsto pelo Mie a partir do efeito no tamanho.", "Se o azul cai dentro da barra vermelha, a cadeia é coerente."],
      example: `Previsto ${nf(C.chain.mie_shift, 1)} nm, observado ${nf(C.chain.peak_shift, 1)} nm (IC ${nf(C.chain.peak_shift_ci95[0], 1)} a ${nf(C.chain.peak_shift_ci95[1], 1)}): coerente.`,
      caution: "Usa só os registros com tamanho e pico relatados juntos." },
    "ca-mie": { what: "Por que o pico quase não muda: a curva de Mie do pico contra o diâmetro, com o tamanho típico com citrato e o tamanho com NaBH₄ marcados.",
      read: ["Faixa dourada: abaixo de ~25 nm a curva é quase plana.", "Pontos: citrato (mediana) e o mesmo tamanho multiplicado pelo efeito do NaBH₄."],
      example: "Reduzir o tamanho de 16 para ~4,5 nm move o pico só ~2 nm: dentro do erro de leitura de um espectro.",
      caution: "" },
    "ca-do": { what: "Efeitos causais na campanha AgNP: como as vazões foram fixadas pelo experimentador (não escolhidas pelo acaso dos artigos), o GP mede diretamente o efeito de aumentar cada uma, do(x + 10 % da faixa).",
      read: ["Um ponto por vazão; abaixo de 1 = aproxima o espectro do alvo; acima = afasta.", "Barra = IC 95 % (covariância conjunta do GP).", "O texto abaixo explica cada efeito em química."],
      example: `AgNO₃ +10 %: perda ×${nf(D.do_effects[0].ratio, 3)}, melhora em ${nf(100 * D.do_effects[0].frac_improve, 0)} % das condições.`,
      caution: "Vale dentro da faixa medida das vazões; fora dela o GP extrapola." },

    /* caracterização */
    "xr-img": { what: "A imagem bruta do detector de raios X: os anéis de difração de um pó de CeO₂ (óxido de cério), um padrão de calibração.",
      read: ["Cor = intensidade (escala log, para ver anéis fracos e fortes juntos).", "Círculos = anéis previstos pelo ajuste da geometria; + = centro ajustado.", "Marque/desmarque \"mostrar anéis ajustados\" para comparar."],
      example: "Cada anel corresponde a uma família de planos cristalinos (índices hkl) da estrutura fluorita do CeO₂.",
      caution: "O quadro mostrado é a média dos 5 quadros, com o dark (sinal sem feixe) subtraído." },
    "xr-3d": { what: "A mesma imagem do detector como relevo 3D: os anéis viram cristas.", read: ["Altura = intensidade (log).", "Gire com o mouse; a imagem foi reduzida para 128 × 128 blocos."],
      example: "As cristas circulares concêntricas mostram que o pó é bem aleatório (anéis contínuos, sem pontos isolados).", caution: "" },
    "xr-prof": { what: "A intensidade média em função da distância ao centro (perfil radial), com os picos atribuídos aos planos da fluorita.",
      read: ["Eixo x: raio em pixels; eixo y: intensidade média no anel daquele raio.", "Marcas: picos indexados, com os índices hkl.", "Picos estreitos e bem separados = boa calibração."],
      example: `${ni(X.geometry.n_rings)} anéis indexados de ${ni(X.geometry.n_predicted)} previstos.`,
      caution: "" },
    "xr-tbl": { what: "A conta da calibração anel por anel: o ângulo 2θ esperado, o raio previsto pelo ajuste e o raio medido.",
      read: ["hkl: o plano cristalino; 2θ: ângulo de difração (lei de Bragg).", "r previsto × r medido, em pixels; resíduo = medido − previsto."],
      example: `Erro RMS de ${nf(X.geometry.rms_residual_px, 2)} pixel: a geometria (feixe de ${nf(X.geometry.energy_keV, 1)} keV, distância de ${ni(X.geometry.distance_px)} px) descreve os anéis com precisão de subpixel.`,
      caution: "O parâmetro de rede do CeO₂ (5,4116 Å, NIST SRM 674b) é tomado como conhecido; é isso que permite calibrar o instrumento." },
    "au-3d": { what: "Nanoaglomerados de ouro fluorescentes (AuNC): tamanho, comprimento de onda de excitação e de emissão, cada ponto um aglomerado relatado.",
      read: ["Três eixos: tamanho (nm), excitação (nm) e emissão (nm).", "Cor = ligante (GSH, outros tióis…).", "Gire com o mouse; passe o mouse para ver o artigo."],
      example: `${ni(U.n)} aglomerados de ${ni(U.n_doi)} artigos; a maioria usa GSH (glutationa) como ligante e emite do vermelho ao infravermelho próximo.`,
      caution: "Aglomerados não têm plásmon: a cor vem de transições moleculares, não da teoria de Mie." },
    "au-T": { what: "A emissão dos nanoaglomerados contra a temperatura de síntese.", read: ["Eixo x: temperatura (°C); eixo y: emissão (nm).", "Cor = ligante."],
      example: "A dispersão vertical num mesmo ponto de temperatura mostra quanto a emissão depende de outras coisas (casca Au(I)–tiolato, agregação).",
      caution: "Temperatura sozinha prevê mal a emissão (veja a aba Variabilidade)." },

    /* sobre */
    "ab-src": { what: "A lista das bases de dados usadas no site, com origem, DOI, volume e licença de uso.",
      read: ["Uma linha por base.", "O DOI leva à publicação original; a licença diz como os dados podem ser reutilizados."],
      example: "Todas são públicas e citáveis; o depósito do projeto (Zenodo) vai seguir o mesmo padrão.", caution: "" },
  };
  const TRY = {
    visao: ["Passe o mouse pela faixa de cores e descubra a partir de que tamanho o ouro deixa de ser vermelho.", "Clique no cartão de achado \"Causalidade\" e confira o efeito do NaBH₄ na aba.", "Na tabela de conferência, procure uma linha amarela e leia por que ela confere só em parte."],
    literatura: ["Escolha Redutor = NaBH₄ e veja o histograma de tamanhos andar para a esquerda.", "Escolha Ligante = CTAB e veja as morfologias não esféricas crescerem.", "No gráfico 3D, clique num ponto isolado e abra o artigo para conferir o valor."],
    optica: ["Clique em \"Turkevich típico\" e compare a cor da cubeta com o alvo.", "Arraste o diâmetro até o espectro sair do alvo e veja J subir no mapa 3D.", "Na inversão bayesiana, ponha o pico em 520 nm e depois em 560 nm e compare a largura do intervalo."],
    designer: ["Clique em \"Carregar\" na primeira sugestão e compare a perda prevista com a melhor medida.", "Troque a superfície para \"incerteza\" e veja onde o modelo sabe pouco.", "No gráfico de calibração, ache o nível em que a curva mais se afasta da diagonal."],
    preditor: ["Clique em \"Turkevich\" e mova o Alvo para 50 nm: veja a probabilidade cair e o \"o que mudar\" sugerir alternativas.", "Mova o Alvo para 3 nm e use o design inverso: clique em \"Carregar\" na primeira receita.", "Marque \"menciona GO\" e veja o que muda na previsão."],
    aprendizado: ["Escolha a campanha AutoAM e compare com a AgNP: onde o GP ganha e onde empata?", "No Kaplan–Meier, compare a curva do GP-UCB com a do aleatório.", "Na tabela-resumo, veja quais resultados perdem o negrito depois da correção de Holm."],
    interpretabilidade: ["Escolha o modelo da literatura e veja qual reagente mais move o tamanho.", "No gráfico de dependência, escolha \"Q sementes\" e observe a mudança de sinal.", "Compare os índices de Sobol com o mapa H²: as mesmas vazões aparecem interagindo?"],
    variabilidade: ["No histograma de Turkevich, compare a faixa de 10–90 % com o tamanho do alvo (20 nm).", "No gráfico 3D de CV, gire até achar a região menos repetível.", "No gráfico artigo novo × síntese nova, veja quantos pontos laranja ficam longe da diagonal."],
    causal: ["No seletor de diagnóstico, escolha \"CTAB\" e veja se as covariáveis ficaram equilibradas.", "No gráfico de replicação, compare as duas bases para o efeito do tiol.", "Leia o gráfico da cadeia e explique por que o pico quase não muda."],
    caracterizacao: ["Desmarque \"mostrar anéis ajustados\" e veja os anéis sozinhos na imagem.", "No perfil radial, passe o mouse sobre os picos e leia os índices hkl.", "No gráfico 3D dos aglomerados, gire até ver a relação entre excitação e emissão."],
    sobre: ["Abra o DOI de uma base e veja a publicação original.", "Leia \"Aguarda as sínteses\" para saber o que o laboratório vai acrescentar."],
  };
  Object.keys(TRY).forEach((t) => { if (TABS[t]) TABS[t].try = TRY[t]; });

  /* ---------------------------------------------------------------------------------------------- conceitos */
  const CONCEPTS = [
    { id: "c-nano", group: "Química e física", title: "O que é uma nanopartícula de ouro", demo: "scale",
      body: "<p>Um nanômetro (nm) é um milionésimo de milímetro. Uma nanopartícula de ouro (AuNP) tem de 1 a 100 nm: milhares a milhões de átomos de ouro. Nessa escala o ouro deixa de ser amarelo e brilhante e fica <b>vermelho</b>, porque os elétrons da superfície oscilam juntos quando a luz verde chega (é o <b>plásmon de superfície</b>, LSPR) e absorvem essa luz.</p><p>O projeto quer partículas de ~20 nm presas ao óxido de grafeno (GO), uma folha de carbono com grupos de oxigênio. A régua abaixo dá a noção de escala.</p>" },
    { id: "c-color", group: "Química e física", title: "Tamanho, espectro e cor", demo: "color",
      body: "<p>O espectrofotômetro UV-Vis mede quanta luz a amostra tira de cada cor (comprimento de onda). O gráfico resultante é o <b>espectro</b>; o ponto mais alto é o <b>pico do plásmon (LSPR)</b>. A teoria de Mie calcula esse espectro a partir do tamanho, com as constantes ópticas medidas do ouro.</p><p>Mova o controle e veja o espectro e a cor mudarem juntos. Repare que entre 5 e 30 nm o pico quase não sai do lugar: só a intensidade por átomo muda.</p>" },
    { id: "c-synth", group: "Química e física", title: "Como se faz uma nanopartícula: redutor, ligante, sementes", demo: "lamer",
      body: "<p>Parte-se de um sal de ouro dissolvido (HAuCl₄, ouro como Au³⁺). Um <b>redutor</b> doa elétrons e transforma Au³⁺ em ouro metálico (Au⁰). Quando há átomos de ouro demais na solução (<i>supersaturação</i>), eles se juntam de repente em <b>núcleos</b>; depois, o ouro restante <b>cresce</b> sobre os núcleos (modelo de LaMer).</p><ul><li><b>Redutor forte</b> (NaBH₄): muitos núcleos de uma vez → muitas partículas pequenas (1–8 nm).</li><li><b>Redutor suave</b> (citrato, Turkevich 1951): poucos núcleos → partículas maiores (10–20 nm).</li><li><b>Ligante</b> (citrato, CTAB, tióis, PVP): cobre a superfície, impede que as partículas grudem e pode escolher a forma.</li><li><b>Sementes</b>: separa as duas etapas (fazer núcleos e depois crescer), dando controle fino do tamanho.</li></ul>" },
    { id: "c-var", group: "Química e física", title: "Por que a mesma receita dá resultados diferentes", demo: null,
      body: "<p>Impurezas dos reagentes, o lote do óxido de grafeno (quantos grupos oxigenados, tamanho das folhas), a água, a velocidade de agitação, o operador… Nada disso costuma estar escrito na receita. O projeto chama isso de <b>variabilidade multi-fonte</b> e propõe medi-la e colocá-la dentro do modelo (o \"contexto do lote\"). A aba Variabilidade mostra o tamanho do problema.</p>" },
    { id: "c-dist", group: "Estatística básica", title: "Média, mediana, quartis e escala logarítmica", demo: "dist",
      body: "<p>A <b>mediana</b> é o valor do meio: metade dos casos abaixo, metade acima. É usada em quase todo o site porque não é puxada por valores extremos (a <b>média</b> é). Os <b>quartis</b> cortam os dados em quatro partes iguais; a faixa entre o 1º e o 3º quartil contém a metade central. \"10–90 %\" é a faixa que contém 80 % dos casos.</p><p>Tamanhos de partícula se espalham por várias ordens de grandeza (2, 20, 200 nm). Na <b>escala logarítmica</b> cada marca é 10× a anterior, e as distribuições ficam simétricas e legíveis. Alterne a escala no exemplo, com os tamanhos reais de Turkevich.</p>" },
    { id: "c-unc", group: "Estatística básica", title: "Incerteza, intervalo de confiança e bootstrap", demo: "boot",
      body: "<p>Qualquer número calculado de uma amostra mudaria um pouco com outra amostra. O <b>intervalo de confiança de 95 % (IC 95 %)</b> é a faixa que, em 95 de 100 amostras, conteria o valor verdadeiro. Quanto mais dados, mais estreito.</p><p>O <b>bootstrap</b> estima essa faixa sem fórmulas: sorteia de novo, com reposição, os próprios dados centenas de vezes e vê quanto o resultado varia. No site, o bootstrap sorteia <b>artigos inteiros</b>, porque sínteses do mesmo artigo não são independentes. Mude o número de artigos no exemplo e veja o IC estreitar.</p>" },
    { id: "c-p", group: "Estatística básica", title: "p-valor, significância e comparações múltiplas", demo: "holm",
      body: "<p>O <b>p-valor</b> responde: se não houvesse diferença nenhuma, qual seria a chance de ver uma diferença tão grande quanto a observada? Abaixo de 0,05 diz-se \"significativo\". Mas ao fazer muitos testes, alguns dão p < 0,05 por puro acaso (com 15 testes, a chance de ao menos um falso positivo passa de 50 %).</p><p>A <b>correção de Holm</b> exige limiares mais duros dos menores p-valores. O exemplo mostra os 15 testes reais da aba Aprendizado: só os pontos abaixo da linha de Holm continuam significativos.</p>" },
    { id: "c-causal", group: "Estatística básica", title: "Correlação não é causa: confundidores e ajuste", demo: "naive",
      body: "<p>Se quem usa NaBH₄ também trabalha mais em temperatura ambiente e com outros ligantes, comparar \"com\" e \"sem\" NaBH₄ mistura tudo isso. Essas variáveis que afetam a escolha do tratamento e o resultado são os <b>confundidores</b>.</p><p>Os métodos causais do site (AIPW, IPW, balanceamento por entropia) dão pesos às sínteses para que os grupos fiquem equilibrados nos confundidores medidos, como num sorteio. O exemplo compara a estimativa ingênua com a ajustada nos quatro efeitos. O <b>E-value</b> diz quão forte teria de ser um confundidor NÃO medido para anular o efeito.</p>" },
    { id: "c-model", group: "Modelos e IA", title: "Modelo, treino e validação: como saber se um modelo presta", demo: "cv",
      body: "<p>Um modelo aprende a relação entre entradas (receita) e saída (resultado) a partir de exemplos. Acertar os exemplos que viu é fácil; o teste honesto é prever exemplos <b>que não viu</b>. Na <b>validação cruzada</b> os dados são divididos em partes; cada parte é prevista por um modelo treinado nas outras.</p><p>O <b>R²</b> é a fração da variação dos dados que o modelo explica (1 = tudo, 0 = nada melhor que a média). No site a validação é por <b>artigo</b> sempre que há vários registros por artigo, para medir o que importa: acertar num laboratório novo.</p>" },
    { id: "c-gp", group: "Modelos e IA", title: "Processo gaussiano e melhoria esperada (o Designer)", demo: "gp",
      body: "<p>O <b>processo gaussiano (GP)</b> é um modelo que, além de prever, diz <b>quanto não sabe</b>: perto de condições medidas a faixa de incerteza é estreita; longe, larga. O núcleo Matérn-5/2 com ARD deixa cada variável ter a sua escala de influência.</p><p>A <b>melhoria esperada (EI)</b> combina previsão e incerteza: vale testar onde a previsão é boa (aproveitar) OU onde a incerteza é grande e pode esconder algo melhor (explorar). O exemplo é uma fatia real do GP da campanha AgNP: média, faixa de 95 % e EI ao longo de uma vazão.</p>" },
    { id: "c-al", group: "Modelos e IA", title: "Aprendizado ativo e análise de sobrevivência", demo: "km",
      body: "<p>No <b>aprendizado ativo</b> o algoritmo escolhe o próximo experimento com base no que já aprendeu, em vez de seguir uma grade fixa. Para medir se isso ajuda, conta-se quantos experimentos são necessários até achar uma condição excelente (top 5 %).</p><p>Algumas tentativas não chegam lá dentro do orçamento. A <b>análise de sobrevivência</b> (Kaplan–Meier) lida com isso sem inventar valores: a curva mostra a fração que ainda não chegou após cada experimento. Arraste o controle do exemplo para ver a curva se formar com as 40 repetições reais do GP-EI no AgNP.</p>" },
    { id: "c-shap", group: "Modelos e IA", title: "SHAP: por que o modelo previu isso?", demo: "shap",
      body: "<p>Os valores de <b>Shapley (SHAP)</b> repartem uma previsão entre as variáveis, de forma justa (vêm da teoria dos jogos): começa-se da previsão média e soma-se a contribuição de cada variável até chegar à previsão daquela síntese. O exemplo mostra essa \"cascata\" para condições reais da campanha AgNP.</p><p>Os <b>índices de Sobol</b> fazem a pergunta global: que fração da variação total cada variável explica, sozinha e em interação.</p>" },
    { id: "c-conf", group: "Modelos e IA", title: "Intervalos que cumprem o que prometem: predição conformal", demo: "conformal",
      body: "<p>Um modelo pode dizer \"90 % de chance de estar entre 7 e 83 nm\" e errar mais do que isso. A <b>predição conformal</b> corrige a faixa usando os erros do próprio modelo em dados que ele não viu, com garantia matemática de cobertura. No Preditor a correção é feita por <b>artigo</b>, então a promessa vale para um laboratório novo.</p>" },
    { id: "c-bayes", group: "Modelos e IA", title: "Raciocínio bayesiano: a priori, verossimilhança e posterior", demo: "bayes",
      body: "<p>A regra de Bayes combina o que se sabia antes (<b>a priori</b>: tamanhos comuns na literatura) com o que a medida diz (<b>verossimilhança</b>: que tamanhos explicam o pico medido) para dar o que se sabe depois (<b>posterior</b>). O exemplo usa a inversão real da aba Óptica: escolha um pico e veja as três curvas.</p>" },
  ];

  /* -------------------------------------------------------------------------------------- como foi feito */
  const HOW = [
    ["Princípio 1: só dados experimentais", "Nada do simulador do projeto entra no site. Todo número vem de uma medida publicada ou de cálculo físico com constantes medidas. Modelos e previsões são marcados como tal. Um teste automático confere que nenhum gerador de dados sintéticos é importado."],
    ["Princípio 2: critério antes do resultado", "Cada escolha de método (núcleo do GP, índice do meio, verossimilhança da inversão, profundidade das árvores) foi decidida por um critério fixado antes, avaliado em dados separados. Alternativas que não melhoraram foram rejeitadas e estão listadas abaixo, com os números."],
    ["Princípio 3: incerteza sempre visível", "Todo resultado tem intervalo (bootstrap por artigo, IC de Greenwood, conformal, posterior). Comparações múltiplas são corrigidas (Holm)."],
    ["1. Dados", `As bases públicas são baixadas e normalizadas por scripts em <span class="mono">tools/data_sources/</span> (reagentes padronizados pelo PubChem; filtros físicos para remover erros de extração). <span class="mono">code/webapp/expdata.py</span> carrega tudo.`],
    ["2. Análises", `<span class="mono">code/webapp/analyses.py</span> roda cada análise (Mie, GP, benchmark, SHAP, causal, preditor…) e grava os resultados em <span class="mono">site/data/*.js</span>.`],
    ["3. Página", `<span class="mono">code/webapp/build_site.py</span> monta <span class="mono">site/index.html</span>. O navegador recalcula ao vivo o GP do Designer, o Mie e a perda J, e as árvores do Preditor, com a mesma conta do Python (conferida por testes).`],
    ["4. Verificação", `${ni(102)} testes automáticos (<span class="mono">python -m pytest code/tests</span>), lint (ruff), conferência de reprodutibilidade (<span class="mono">tools/check_repo.py --regen</span>) e integração contínua no GitHub. A acessibilidade foi conferida com axe-core e o layout em celular.`],
    ["5. Reproduzir", `<span class="mono">source .venvs/core/bin/activate; python code/webapp/build_site.py</span> refaz tudo (~5 min); <span class="mono">--reuse</span> só remonta a página.`],
  ];
  const DECISIONS = [
    ["Índice de refração do meio", "Ajustar n entre 1,333 e 1,39", "rejeitado: ganha décimos de nm na validação e se afasta de Haiss; mantida a água"],
    ["Núcleo do GP", "Matérn-1/2, 3/2, 5/2, RBF e ruído medido, mesmas 10 dobras, NLPD", "os núcleos empatam (Δ < 0,05); mantido o Matérn-5/2 da proposta; o ruído medido piora muito"],
    ["Modelo de tamanho da literatura", "9 variáveis (1º reagente citado) × 28 (presença de cada reagente); validação por artigo", `adotado: +${nf(v(() => I.literature.boot.diff.value), 2)} no R² por artigo (IC exclui zero)`],
    ["Alvo dos nanoaglomerados", "Emissão direta × deslocamento de Stokes", "mantido Stokes pela física; ganho dentro do ruído (IC inclui zero) e o site diz isso"],
    ["Definição de Turkevich", "\"citrato citado primeiro\" × \"citrato como único redutor\"", "adotado: único redutor (mediana 16,0 nm = Frens)"],
    ["Profundidade das árvores do Preditor", "3, 5, 6 e sem limite; perda quantílica por artigo", "mantida 3: a diferença foi de 0,3 %"],
    ["Efeito aleatório por receita", "Encolhimento empírico-bayesiano do resíduo de cada receita", "rejeitado: ganho de 0,4 % na perda, menor que o ruído"],
    ["Verossimilhança da inversão pico → tamanho", "Gaussiana × t de Student (ν = 10, 5, 3, 2), cobertura do IC 90 %", `adotada t com ν = ${O.inversion.nu} (cobertura ${nf(100 * O.inversion.coverage90, 0)} %; gaussiana ${nf(100 * O.inversion.scan[0].coverage90, 0)} %)`],
    ["Base de nanoaglomerados na análise causal", "Incluir × excluir", "excluída: foi selecionada pelo produto (viés de seleção) e quase todo aglomerado usa tiol"],
  ];
  const LIMITS = [
    "Os dados da literatura vêm de mineração de texto: há erros de extração; os filtros físicos tiram os grosseiros, não todos.",
    "Na base Cruse et al. o tamanho é um por artigo e se repete nos parágrafos; isso dilui contrastes.",
    "A análise causal é observacional: ajusta só os confundidores medidos (o E-value mede a robustez ao resto).",
    "A campanha do Designer é de prata, não de ouro sobre GO: demonstra o método, não o produto do projeto.",
    "Tudo que depende das sínteses GO–AuNP do projeto (lotes de GO, MISO, campanha prospectiva, TEM) aguarda o laboratório.",
  ];

  /* ------------------------------------------------------------------------------------------ glossário */
  const GLOSS = [
    ["AIPW", "Estimador causal \"duplamente robusto\": combina um modelo do resultado com pesos de propensão; fica correto se um dos dois estiver certo."],
    ["a priori / posterior", "O que se sabe antes e depois de ver a medida, na regra de Bayes."],
    ["AuNC", "Nanoaglomerado de ouro (< 2 nm): poucas dezenas de átomos, não tem plásmon e emite luz (fluorescente)."],
    ["AuNP", "Nanopartícula de ouro (1–100 nm)."],
    ["Bootstrap", "Sortear de novo os próprios dados, com reposição, para medir a incerteza de um resultado."],
    ["Censura", "Quando o evento (achar o top 5 %) não aconteceu até o fim do orçamento: sabe-se só que levaria mais."],
    ["CI / IC 95 %", "Intervalo de confiança: faixa que contém o valor verdadeiro em 95 % das amostras possíveis."],
    ["Confundidor", "Variável que afeta tanto a escolha do tratamento quanto o resultado, e engana comparações simples."],
    ["Conformal", "Método que ajusta faixas de previsão usando erros em dados não vistos, garantindo a cobertura."],
    ["CRPS", "Nota de uma previsão probabilística inteira (centro e largura); menor é melhor."],
    ["CTAB", "Surfactante catiônico que adsorve em certas faces do ouro e favorece bastões e outras formas."],
    ["CV (coeficiente de variação)", "Desvio padrão dividido pela média: o ruído relativo."],
    ["DAG", "Grafo acíclico dirigido: o diagrama de setas causais."],
    ["DOI", "Identificador permanente de um artigo; clicar leva à publicação."],
    ["E-value", "Quão forte teria de ser um confundidor não medido para anular o efeito estimado."],
    ["EI (melhoria esperada)", "Quanto se espera melhorar o melhor resultado ao testar uma condição; equilibra explorar e aproveitar."],
    ["Escore de propensão", "Chance de uma síntese receber o tratamento, dadas as suas outras características."],
    ["Extinção", "Luz removida do feixe pela amostra (absorção + espalhamento)."],
    ["GO", "Óxido de grafeno: folha de carbono com grupos de oxigênio, o suporte das AuNP no projeto."],
    ["GP", "Processo gaussiano: modelo que prevê e informa a própria incerteza."],
    ["H² de Friedman", "Fração do efeito conjunto de duas variáveis que vem da interação entre elas."],
    ["Holm", "Correção para muitos testes ao mesmo tempo, que evita falsos positivos."],
    ["I²", "Fração da diferença entre estudos (ou bases) que não é acaso."],
    ["Kaplan–Meier", "Curva da fração que ainda não teve o evento ao longo do tempo, aceitando censura."],
    ["LSPR", "Ressonância de plásmon de superfície localizada: o pico de absorção que dá a cor ao ouro."],
    ["Matérn-5/2, ARD", "Núcleo do GP (quão suave é a função) com uma escala de influência para cada variável."],
    ["Mediana", "Valor do meio: metade dos casos abaixo, metade acima."],
    ["Mie", "Solução exata da física de uma esfera iluminada; dá o espectro a partir do tamanho e do material."],
    ["MISO", "Otimização com várias fontes de informação de custos diferentes (UV-Vis barato, TEM caro)."],
    ["NaBH₄", "Boro-hidreto de sódio, redutor forte: partículas pequenas."],
    ["NLPD", "Log-verossimilhança preditiva negativa: nota que pune erro e incerteza mal calibrada."],
    ["Perda J", "Distância entre o espectro obtido e o espectro-alvo (Eq. 1 do pré-registro); 0 = idêntico."],
    ["PIT", "Posição da medida dentro da distribuição prevista; uniforme se o modelo está calibrado."],
    ["p-valor", "Chance de ver uma diferença tão grande se não houvesse diferença real."],
    ["Quartis", "Valores que dividem os dados em quatro partes iguais."],
    ["R²", "Fração da variação dos dados explicada pelo modelo."],
    ["Regressão quantílica", "Modelo que prevê percentis (5 %, 50 %, 95 %…) em vez da média."],
    ["RMST", "Tempo médio restrito: número médio de experimentos gastos até o evento, contando no máximo o orçamento."],
    ["SHAP", "Divisão justa de uma previsão entre as variáveis (valores de Shapley)."],
    ["SMD", "Diferença média padronizada entre grupos; |SMD| < 0,1 = equilibrado."],
    ["Sobol (S1, ST)", "Fração da variância explicada por uma variável sozinha (S1) e com interações (ST)."],
    ["Stokes (deslocamento)", "Diferença entre o comprimento de onda emitido e o de excitação."],
    ["TEM", "Microscopia eletrônica de transmissão: mede o tamanho das partículas diretamente."],
    ["Top 5 %", "As condições com os 5 % melhores resultados de uma campanha."],
    ["Turkevich", "Síntese clássica (1951) com citrato em água fervente: AuNP de ~15–20 nm."],
    ["UV-Vis", "Espectroscopia no ultravioleta e visível: mede a absorção da amostra em cada cor."],
    ["Validação cruzada", "Testar o modelo em partes dos dados que ele não viu ao treinar."],
  ];
  const REFS = [
    "Turkevich, Stevenson & Hillier (1951). Discuss. Faraday Soc. 11, 55 — síntese com citrato.",
    "Frens (1973). Nature Phys. Sci. 241, 20 — controle do tamanho pela razão citrato:ouro.",
    "Brust et al. (1994). J. Chem. Soc., Chem. Commun., 801 — NaBH₄ + tiol, partículas de 1–3 nm.",
    "Jana, Gearheart & Murphy (2001). Adv. Mater. 13, 1389 — crescimento mediado por sementes.",
    "Nikoobakht & El-Sayed (2003). Chem. Mater. 15, 1957 — bastões com CTAB.",
    "Johnson & Christy (1972). Phys. Rev. B 6, 4370 — constantes ópticas do ouro.",
    "Haiss et al. (2007). Anal. Chem. 79, 4215 — tamanho a partir do espectro UV-Vis.",
    "Cruse et al. (2022). Sci. Data — base de sínteses de AuNP por mineração de texto.",
    "Mekki-Berrada et al. (2021). npj Comput. Mater. 7, 55 — campanha AgNP em microfluídica.",
    "Liang et al. (2021). npj Comput. Mater. 7, 188 — benchmark de otimização bayesiana em materiais.",
    "Lundberg & Lee (2017). NeurIPS — SHAP.",
    "Saltelli et al. (2010). Comput. Phys. Commun. 181, 259 — índices de Sobol.",
    "Romano, Patterson & Candès (2019). NeurIPS — regressão quantílica conformal (CQR).",
    "Kaplan & Meier (1958). JASA 53, 457 — estimador de sobrevivência.",
    "Holm (1979). Scand. J. Statist. 6, 65 — correção para comparações múltiplas.",
    "Hainmueller (2012). Political Analysis 20, 25 — balanceamento por entropia.",
    "VanderWeele & Ding (2017). Ann. Intern. Med. 167, 268 — E-value.",
    "DerSimonian & Laird (1986). Control. Clin. Trials 7, 177 — efeitos aleatórios.",
    "Gneiting & Raftery (2007). JASA 102, 359 — regras de pontuação (CRPS).",
  ];
  return { TABS, FIG, CONCEPTS, HOW, DECISIONS, LIMITS, GLOSS, REFS, nTabs };
};
